### ISSUE TITLE
matrix contains invalid numeric entries?

### ISSUE THREAD

**Issue by ddwhzh** [kakaobrain/sparse-detr#2]
When I try to test with the pre-trained model, an error reported *matrix contains invalid numeric entries*, due to backbone output is nan, is there any solution?

**Comment by prayforher** [comment]
Can you tell us which pre-trained model did not work?

**Comment by ddwhzh** [comment]
sparse_detr_r50_10.pth

**Comment by prayforher** [comment]
I've succeeded again in evaluating the model you mentioned.
I think there is no issue in evaluating the model with the current code.

---

Which command did you use for evaluation? 
If you want to evaluate the model trained on ResNet, you should use the command as follows:

> $ ./configs/r50_sparse_detr_rho_0.1.sh --resume `<path to sparse_detr_r50_10.pth>` --eval

**Comment by ddwhzh** [comment]
OK, i will try, thx.
