### ISSUE TITLE
RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1639180594101/work/torch/csrc/jit/ir/alias_analysis.cpp":584, please report a bug to PyTorch. We don't have an op for aten::fill_ but it isn't a special case.  Argument types: Tensor, bool, 

### ISSUE THREAD

**Issue by ZiMo-Chen** [kakaobrain/sparse-detr#5]
RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1639180594101/work/torch/csrc/jit/ir/alias_analysis.cpp":584, please report a bug to PyTorch. We don't have an op for aten::fill_ but it isn't a special case.  Argument types: Tensor, bool,

**Comment by EherSenaw** [comment]
I had exactly same error when trying to train model with following command:
```
GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 1 python main.py \
    --with_box_refine \
    --two_stage \
    --eff_query_init \
    --eff_specific_head \
    --rho 0.1 \
    --use_enc_aux_loss \
    --coco_path {MY_OWN_COCO_PATH} \
    --output_dir {MY_OWN_OUTPUT_DIR_PATH}
```
Is their anyone dealt with this?

Thanks.

**Comment by cxq1** [comment]
> I had exactly same error when trying to train model with following command:
> 
> ```
> GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 1 python main.py \
>     --with_box_refine \
>     --two_stage \
>     --eff_query_init \
>     --eff_specific_head \
>     --rho 0.1 \
>     --use_enc_aux_loss \
>     --coco_path {MY_OWN_COCO_PATH} \
>     --output_dir {MY_OWN_OUTPUT_DIR_PATH}
> ```
> 
> Is their anyone dealt with this?
> 
> Thanks.

**Comment by ZiMo-Chen** [comment]
> 尝试使用以下命令训练模型时出现完全相同的错误：
> 
> ```
> GPUS_PER_NODE=1 ./tools/run_dist_launch.sh 1 python main.py \
>     --with_box_refine \
>     --two_stage \
>     --eff_query_init \
>     --eff_specific_head \
>     --rho 0.1 \
>     --use_enc_aux_loss \
>     --coco_path {MY_OWN_COCO_PATH} \
>     --output_dir {MY_OWN_OUTPUT_DIR_PATH}
> ```
> 
> 他们的任何人都处理过这个吗？
> 
> 谢谢。

There may be a problem with the compute_GFLOP function, which I made the code run by removing the call to that function

**Comment by EherSenaw** [comment]
> 

Thanks. I would try out.
